// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiTe_nBJz9tX6OogpNxvRVtpjixIfr1cU',
    appId: '1:1000747317207:web:76c983595d72f22f6a7d92',
    messagingSenderId: '1000747317207',
    projectId: 'construction-management-4229e',
    authDomain: 'construction-management-4229e.firebaseapp.com',
    storageBucket: 'construction-management-4229e.firebasestorage.app',
    measurementId: 'G-DN0XF58T90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnqn3suluaXu68umqTZAHAn-IgqFSAbIM',
    appId: '1:1000747317207:android:a9fe27924592bed06a7d92',
    messagingSenderId: '1000747317207',
    projectId: 'construction-management-4229e',
    storageBucket: 'construction-management-4229e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfcR7XdRI8h-_nJKhbsj86w5jUEDiNBjQ',
    appId: '1:1000747317207:ios:141bd02449b74f806a7d92',
    messagingSenderId: '1000747317207',
    projectId: 'construction-management-4229e',
    storageBucket: 'construction-management-4229e.firebasestorage.app',
    iosBundleId: 'com.example.constructionCompanyApp',
  );
}
